[package]
authors = ["Jan Gosmann <jan.gosmann@tngtech.com>"]
edition = "2018"
name = "day18-rust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rstest = "0.12.0"
