[package]
name = "day07-rust"
version = "0.1.0"
authors = ["Jan Gosmann <jan.gosmann@tngtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
